micronaut:
  application:
    name: nexo
nexo:
  session:
    store: map
datasources:
  default:
    url: jdbc:postgresql://192.168.50.141:5432/nexo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
