micronaut:
  application:
    name: nexo
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://192.168.50.141:5432/nexo
    username: postgres
jpa:
  default:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        hbm2ddl:
          auto: update
        show_sql: true
        use_sql_comments: true
nexo:
  oauth2:
    enabled: true
  oidc:
    enabled: true
    login-page-uri: http://localhost:5173/auth
    oauth-consent-page-uri: "http://localhost:5173/consent/oauth"
    oidc-consent-page-uri: "http://localhost:5173/consent/oidc"
    rsa-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDBHNcmsBvK5I4GSflhB55SOQvqLz6M3BfcDWtt4jW7H8W8LkOGS1FAl7d7+JoTMeVjWzMVXLJySpeqIgeAXDlJekWjoU5rAFGYQk6f6aD1Oh245sCjFsb1ddaGLNLUlAh95bJ3fQPqD9Of62Izp8jMTYPP8dLKo5ORSqsr/cgtSEfadi1RwQxOqwWzEYKkvV7SNZMM3aLtqpvhJxMIsIykmxengqQo47B68HifQmg2UGBalwBdh5RlbUqRSH09iFYkFswApPIFlhhBB+MvPpbTAc8Z5Ja05o5Qm4JpkHilS09wZV/YeW0+fFgJsLgZMsgk2X81M6ZJG4Mz3tBNXh+BAgMBAAECggEALBI1Zb5mMVkUsom6UHMJJjGfrvvGNiZaiZ1Eaajo40IegdI7FdBlhCy7sp6rJvtJovGiyFrF3MB6OVkXxisF5edyMiQzfcbuWCW1xNfwJFb1hoee6fleQZF5eliLavk3sOe1YYCV3pprDQGOgURm1n1QOioxlY5cNJnKU7lQsEh64p5mSuU1XgK8ShTIwdtMEi4IfbtE2MlY5uqAL0V8LEEOsXDjk0mxY9K5H3LmIsdoEtcdsG/4ywUHzrRiNqHkzCswdurt/AIAp757F+sH254/W7NB+spyWZILzUQgzR1JH79hJGbNrVEdzBoD4G6GVUdnP7T5qeBFj8uI5zI4WwKBgQD7Q7WiJpUuKGx7NWMgl2cK2BkyGruG7jjU7qZ2+wvPNMlCESvYk9hNlHXlhm3xc+2xfBoWe1QVJRkyW4XLbIlcAkZjKI1df9FEaEFC7/xBoBjbpJ/GG8d2c5ZFo0OhtvDyO9qZ9+0AKglL+b3AO1bAbjBDaLxQ5QzZg+zF6Jwx+wKBgQDEwI/4FUv00yJjWV4gn2PD/IoiUkEC8nm7pWDDUm5YZ1oJyJDAMmPbgpPbNq4ujRfYNZS9LvcMAeH3TMUm9ckhYPKjztWBHRyHV1twGcW0S2Sd4KD7qXOg0+Y1LZ2IgjGOAwZJPW5cJlkYywiT83zVUWNuzatEQo2fxGo4Jmr3swKBgQD2InrgD9mdML4r571mJMos5kmwOl2vLNeBRxLMhNoprXTlgjqoWxPN03u2TvyORVj3vzEzCrbwS7omCV/ESVs5RYU8B3KLv/T4hQRBFSPQCYuwRdC52WaIU2xGZUuQM8xODnHy19pTido3kbref4JY2NfwgL3QpL/0p/YeXOH9VwKBgFQShHJZh09iOLuDIHmIIjVI4C2yQB1mRyYrkKFlw8j6wLqVfWTjI1BVB6EQSHWTzLCSlLASNXZoB4qIv2XaeMtOheABLbIyIlKivWu1V4mm/aOIrMFcsw/x+9iVWU9PcqVgHXuGSHYP3Np/R3cRADKWyIo8UAam+aVfZJQBtouJAoGBAM6LcEJVyXyAVFdTolSBUt/X3ApBaD37H+v0PhCIIgtWSGg09+6Pfv+cLDUDMoGhxCXUSeF/y+NB4zB7j8+scFeZiA+WKpGFTUqJInLafLKlUG/2IWh24Ma8ReuGvRhC78KK0OEW+OhmP+hBLNbyinZbVm0lcga8u6A0+2cRTOK/
    rsa-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwRzXJrAbyuSOBkn5YQeeUjkL6i8+jNwX3A1rbeI1ux/FvC5DhktRQJe3e/iaEzHlY1szFVyyckqXqiIHgFw5SXpFo6FOawBRmEJOn+mg9ToduObAoxbG9XXWhizS1JQIfeWyd30D6g/Tn+tiM6fIzE2Dz/HSyqOTkUqrK/3ILUhH2nYtUcEMTqsFsxGCpL1e0jWTDN2i7aqb4ScTCLCMpJsXp4KkKOOwevB4n0JoNlBgWpcAXYeUZW1KkUh9PYhWJBbMAKTyBZYYQQfjLz6W0wHPGeSWtOaOUJuCaZB4pUtPcGVf2HltPnxYCbC4GTLIJNl/NTOmSRuDM97QTV4fgQIDAQAB
  security:
    session:
      cookie-name: NEXO_SESSION
      cookie-same-site: LAX
      cookie-secure: false
      cookie-transport-enabled: true
      header-transport-enabled: true
      redis-local-cache-enabled: true
      redis-local-cache-maximum-size: 10000
      redis-local-cache-ttl: 30s
      redis-cluster-index-shards: 64
      store: redis
    csrf:
      enabled: true
      session-attribute-name: CSRF_TOKEN
      exclude-paths:
      - /csrf
      - /oauth/token
      - /oidc/token
      header-name: X-CSRF-Token
    password-encoder: bcrypt
redis:
  uri: redis://192.168.50.144:6379
